'use client';

import { Roboto } from 'next/font/google';
import { createGlobalStyle } from 'styled-components';

import Header from '@/components/Header';
import ToastProvider from '@/providers/ToastProvider';
import ClientOnly from '@/components/ClientOnly';

const roboto = Roboto({
  weight: ['400'],
  subsets: ['latin'],
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const GlobalStyles = createGlobalStyle`
  :root {
    --clr-white: #fff;
    --clr-primary-black: #000;
    --clr-secondary-black: #222;
    --clr-primary-blue: #5542f6;
  }

  *,
  *::after,
  *::before {
    margin: 0;
    padding: 0;
    -webkit-box-sizing: inherit;
    box-sizing: inherit;
  }

  html {
    font-size: 62.5%;
    -webkit-box-sizing: border-box;
    box-sizing: border-box;
  }

  body {
    font-size: 1.6rem;
    background-color: #f0f0f0;
    color: #222;
  }
`;

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <ClientOnly>
          <GlobalStyles />
          <Header />
          <ToastProvider />
        </ClientOnly>
        {children}
      </body>
    </html>
  );
};
