'use client';

import { Roboto } from 'next/font/google';
import { createGlobalStyle } from 'styled-components';

import Header from '@/components/Header';
import './globals.css';

const roboto = Roboto({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const GlobalStyles = createGlobalStyle`
  /* @import url('https://fonts.googleapis.com/css2?family=Roboto&display=swap'); */
  body {
    margin: 0;
    padding: 0;
  }
`;

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <GlobalStyles />
        <Header />
        {children}
      </body>
    </html>
  );
};
